import {loadEnv, type BackendEnv} from "../config";

export type PreviewEngine = "hyperframes" | "remotion";

export type RenderConfig = {
  PREVIEW_ENGINE: PreviewEngine;
  ENABLE_HYPERFRAMES_PREVIEW: boolean;
  ENABLE_LEGACY_OVERLAY: boolean;
  ENABLE_LIVE_BROWSER_OVERLAY: boolean;
  ENABLE_REMOTION_PREVIEW: boolean;
  ENABLE_AUDIO_ONLY_PREVIEW: boolean;
  ENABLE_DARK_AUDIO_PREVIEW: boolean;
  ENABLE_BLACK_PREVIEW_BACKGROUND: boolean;
  ENABLE_MANIFEST_TYPOGRAPHY: boolean;
  ENABLE_FONT_GRAPH: boolean;
  ENABLE_MILVUS_ANIMATION_RETRIEVAL: boolean;
  ENABLE_SERVER_RENDERED_PREVIEW: boolean;
  ENABLE_PREVIEW_DIAGNOSTICS: boolean;
  ENABLE_PREVIEW_PIPELINE_TRACE: boolean;
};

export const resolveRenderConfigFromEnv = (env: BackendEnv): RenderConfig => {
  return {
    PREVIEW_ENGINE: env.PREVIEW_ENGINE,
    ENABLE_HYPERFRAMES_PREVIEW: env.ENABLE_HYPERFRAMES_PREVIEW,
    ENABLE_LEGACY_OVERLAY: env.ENABLE_LEGACY_OVERLAY,
    ENABLE_LIVE_BROWSER_OVERLAY: env.ENABLE_LIVE_BROWSER_OVERLAY,
    ENABLE_REMOTION_PREVIEW: env.ENABLE_REMOTION_PREVIEW,
    ENABLE_AUDIO_ONLY_PREVIEW: env.ENABLE_AUDIO_ONLY_PREVIEW,
    ENABLE_DARK_AUDIO_PREVIEW: env.ENABLE_DARK_AUDIO_PREVIEW,
    ENABLE_BLACK_PREVIEW_BACKGROUND: env.ENABLE_BLACK_PREVIEW_BACKGROUND,
    ENABLE_MANIFEST_TYPOGRAPHY: env.ENABLE_MANIFEST_TYPOGRAPHY,
    ENABLE_FONT_GRAPH: env.ENABLE_FONT_GRAPH,
    ENABLE_MILVUS_ANIMATION_RETRIEVAL: env.ENABLE_MILVUS_ANIMATION_RETRIEVAL,
    ENABLE_SERVER_RENDERED_PREVIEW: env.ENABLE_SERVER_RENDERED_PREVIEW,
    ENABLE_PREVIEW_DIAGNOSTICS: env.ENABLE_PREVIEW_DIAGNOSTICS,
    ENABLE_PREVIEW_PIPELINE_TRACE: env.ENABLE_PREVIEW_PIPELINE_TRACE
  };
};

export const loadRenderConfig = (overrides?: Partial<NodeJS.ProcessEnv>): RenderConfig => {
  return resolveRenderConfigFromEnv(loadEnv(overrides));
};
