import type {CreativeAsset} from "../types";

export const SAMPLE_CREATIVE_ASSETS: CreativeAsset[] = [
  {
    id: "asset_warning_badge_001",
    name: "Warning Badge",
    type: "icon",
    tags: ["warning", "mistake", "risk", "problem", "caution"],
    keywords: ["mistake", "warning", "risk", "error"],
    semanticDescription: "A compact badge for caution, problem, or mistake moments.",
    visualStyle: ["minimal", "bold", "editorial"],
    colors: ["#EF4444", "#111827", "#FFFFFF"],
    hasTextSlot: false,
    motionCompatible: true,
    supportsTransparency: true,
    renderCost: "low",
    defaultDurationMs: 1200
  },
  {
    id: "asset_growth_graph_001",
    name: "Growth Graph",
    type: "ui-card",
    tags: ["growth", "scale", "progress", "business", "metric"],
    keywords: ["growth", "scale", "increase", "progress", "metric"],
    semanticDescription: "A clean KPI-style card for growth, scaling, and measurable progress.",
    visualStyle: ["premium", "clean", "cinematic"],
    colors: ["#0F172A", "#E2E8F0", "#38BDF8"],
    aspectRatio: "16:9",
    hasTextSlot: true,
    textSlotIds: ["headline", "subline"],
    motionCompatible: true,
    supportsTransparency: true,
    renderCost: "medium",
    defaultDurationMs: 1800
  },
  {
    id: "asset_bottleneck_pipeline_001",
    name: "Bottleneck Pipeline",
    type: "three-scene",
    tags: ["bottleneck", "constraint", "flow", "pipeline", "system"],
    keywords: ["bottleneck", "constraint", "pipeline", "flow"],
    semanticDescription: "A depth-heavy pipeline scene for blockage and constraint moments.",
    visualStyle: ["cinematic", "depth", "technical"],
    colors: ["#0B1220", "#93C5FD", "#FFFFFF"],
    aspectRatio: "16:9",
    hasTextSlot: true,
    textSlotIds: ["headline"],
    motionCompatible: true,
    supportsTransparency: true,
    renderCost: "high",
    defaultDurationMs: 2200
  },
  {
    id: "asset_glass_callout_001",
    name: "Glass Callout",
    type: "ui-card",
    tags: ["callout", "glass", "panel", "quote", "support"],
    keywords: ["callout", "glass", "panel", "highlight"],
    semanticDescription: "A translucent card for supporting text and editorial callouts.",
    visualStyle: ["glass", "premium", "soft"],
    colors: ["#FFFFFF", "#CBD5E1", "#2563EB"],
    hasTextSlot: true,
    textSlotIds: ["headline", "support"],
    motionCompatible: true,
    supportsTransparency: true,
    renderCost: "low",
    defaultDurationMs: 1500
  },
  {
    id: "asset_keyword_circle_001",
    name: "Keyword Circle",
    type: "shape",
    tags: ["keyword", "circle", "underline", "emphasis", "highlight"],
    keywords: ["keyword", "circle", "highlight", "emphasis"],
    semanticDescription: "A minimalist shape for keyword emphasis and underline-style motion.",
    visualStyle: ["minimal", "graphic", "clean"],
    colors: ["#FACC15", "#111827"],
    hasTextSlot: false,
    motionCompatible: true,
    supportsTransparency: true,
    renderCost: "low",
    defaultDurationMs: 900
  },
  {
    id: "asset_depth_grid_001",
    name: "Depth Grid",
    type: "lottie",
    tags: ["depth", "grid", "background", "premium", "tech"],
    keywords: ["grid", "depth", "background", "premium"],
    semanticDescription: "A subtle grid for background depth and movement.",
    visualStyle: ["editorial", "subtle", "ambient"],
    colors: ["#0B1220", "#1D4ED8", "#60A5FA"],
    hasTextSlot: false,
    motionCompatible: true,
    supportsTransparency: true,
    renderCost: "medium",
    defaultDurationMs: 2400
  },
  {
    id: "asset_title_plate_001",
    name: "Title Plate",
    type: "ui-card",
    tags: ["title", "hook", "hero", "statement", "opening"],
    keywords: ["title", "hook", "opening", "statement"],
    semanticDescription: "A hero-style title card for opening beats or section headers.",
    visualStyle: ["hero", "minimal", "premium"],
    colors: ["#0F172A", "#FFFFFF", "#F59E0B"],
    hasTextSlot: true,
    textSlotIds: ["title", "subline"],
    motionCompatible: true,
    supportsTransparency: true,
    renderCost: "medium",
    defaultDurationMs: 1600
  },
  {
    id: "asset_transition_sweep_001",
    name: "Transition Sweep",
    type: "lottie",
    tags: ["transition", "sweep", "bridge", "motion", "movement"],
    keywords: ["transition", "sweep", "bridge", "movement"],
    semanticDescription: "A clean sweep used to bridge between moments.",
    visualStyle: ["cinematic", "minimal", "bridge"],
    colors: ["#FFFFFF", "#93C5FD", "#0B1220"],
    hasTextSlot: false,
    motionCompatible: true,
    supportsTransparency: true,
    renderCost: "low",
    defaultDurationMs: 1000
  }
];

